package com.talentomobile.assignment.dbdata.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.talentomobile.assignment.dbdata.db.PlaceDB;

import com.talentomobile.assignment.dbdata.db.dao.PlaceDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig placeDBDaoConfig;

    private final PlaceDBDao placeDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        placeDBDaoConfig = daoConfigMap.get(PlaceDBDao.class).clone();
        placeDBDaoConfig.initIdentityScope(type);

        placeDBDao = new PlaceDBDao(placeDBDaoConfig, this);

        registerDao(PlaceDB.class, placeDBDao);
    }
    
    public void clear() {
        placeDBDaoConfig.clearIdentityScope();
    }

    public PlaceDBDao getPlaceDBDao() {
        return placeDBDao;
    }

}
