package com.talentomobile.assignment.dbdata.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PLACE_DB".
 */
@Entity
public class PlaceDB {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Double east;
    private Double south;
    private Double north;
    private Double west;
    private Double lat;
    private Double lng;
    private String countryCode;
    private Integer population;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PlaceDB() {
    }

    public PlaceDB(Long id) {
        this.id = id;
    }

    @Generated
    public PlaceDB(Long id, String name, Double east, Double south, Double north, Double west, Double lat, Double lng, String countryCode, Integer population) {
        this.id = id;
        this.name = name;
        this.east = east;
        this.south = south;
        this.north = north;
        this.west = west;
        this.lat = lat;
        this.lng = lng;
        this.countryCode = countryCode;
        this.population = population;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getEast() {
        return east;
    }

    public void setEast(Double east) {
        this.east = east;
    }

    public Double getSouth() {
        return south;
    }

    public void setSouth(Double south) {
        this.south = south;
    }

    public Double getNorth() {
        return north;
    }

    public void setNorth(Double north) {
        this.north = north;
    }

    public Double getWest() {
        return west;
    }

    public void setWest(Double west) {
        this.west = west;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public Integer getPopulation() {
        return population;
    }

    public void setPopulation(Integer population) {
        this.population = population;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
